Exposed package deploy as github action
microsoft/powerplatform-actions pull request #79
Opened 2021-05-11 16:36 UTC by Dee-pak

2021-05-11 16:42 UTC, Dee-pak commented on .github/workflows/rolling-instance-actions.yml
> +        package: ''
I am not entirely sure what should be the path to the package here for rolling-instance-actions.

2021-05-18 21:09 UTC, davidjenni commented
once the pac CLI update in #82 has merged, refresh this branch/PR. I hope it will reduce the "files changed" back to a non-noisy number again. :-) If not, pls remove/reset the last commit (that also refreshed the CLI) to this branch

2021-05-18 21:23 UTC, davidjenni requested changes

2021-05-18 21:23 UTC, davidjenni commented on deploy-package/action.yml
> +description: 'Power Platform package deploy - Deploys the package dll or the zip file with a package.'
add verbiage that deploy is only supported on Windows runners; the action itself should fail but nice to tell this important detail upfront :-)

2021-05-18 21:23 UTC, davidjenni commented on src/test/data/pkgDeployTestData/PkgFolder/Content/en-us/EndHtml/HTML/Default.htm
> +﻿<html xmlns="http://www.w3.org/1999/xhtml">
please remove all the Content/ parts of the package folder in TestData. It doesn't (or at least, shouldn't) participate in the actual deploy part, as those files are more commonly used for AppSource publishing and deployment (which is way beyond of what this new deploy action does)

2021-05-18 21:23 UTC, davidjenni commented on deploy-package/action.yml
> +  log-file:
these 2 pac CLI params for logging should NOT be exposed to the action user. Instead, we should do "the right thing (TM)" which is:
we always log to console AND we set the logfile path to a known location and upload it as part of the job's artifact. There is an npm module to do so from within an action:
https://www.npmjs.com/package/@actions/artifact#Upload-an-Artifact

https://github.com/actions/toolkit/tree/main/packages/artifact

2021-05-18 21:23 UTC, davidjenni commented on src/actions/deploy-package/index.ts
> +        const logToConsole = core.getInput('log-console', { required: false });
see my comments in action.yaml re: logConsole and logFile

2021-05-19 17:34 UTC, davidjenni approved these changes

2021-05-19 20:13 UTC, merged